pipeline {
    agent any
    stages {
        stage('Example') {
            steps {
                echo 'Hello World'

                script {
                    def browsers = ['Bir', 'iki', 'uc']
                    for (int i = 0; i < browsers.size(); ++i) {
                        echo "${browsers[i]}"
                    }
                }
            }
        }
    }
}